name: ds-portfolio
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - jupyterlab
  - pytest
  - pip
  - pip:
      - seaborn
      - xgboost
      - lightgbm
      - category-encoders
      - shap
      - streamlit
      - fastapi
      - uvicorn[standard]
